[package]
name = "lc"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
clap = "3.0.0-beta.5"
glob = "0.3.0"
ignore = "0.4.18"
rayon = "1.5.1"
