[package]
name = "lc"
version = "0.3.0"
edition = "2021"

[profile.release]
opt-level = "s"
panic = "abort"
lto = "fat"
strip = "symbols"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
ignore = "0.4.22"
rayon = "1.10.0"
